steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/foodtok-backend-repo/foodtok-backend', '.']
  env:
    - "VITE_DB_USER=$$USER"
    - "VITE_DB_DATABASE=$$USER"
    - "VITE_DB_PASSWORD=$$PASS"
    - "VITE_DB_PORT=$$PORT"
    - "VITE_DB_HOST=$$URL"
    - "VITE_SUPABASE_URL=$$URL"
    - "VITE_SUPABASE_KEY=$$KEY"
  secretEnv: ['USER', 'PASS', 'PORT', 'URL', 'KEY']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/Foodtok_DB_USER/versions/1
    env: 'USER'
  - versionName: projects/$PROJECT_ID/secrets/Foodtok_DB_PASSWORD/versions/1
    env: 'PASS'
  - versionName: projects/$PROJECT_ID/secrets/Foodtok_DB_PORT/versions/1
    env: 'PORT'
  - versionName: projects/$PROJECT_ID/secrets/Foodtok_SUPABASE_URL/versions/1
    env: 'URL'
  - versionName: projects/$PROJECT_ID/secrets/Foodtok_SUPABASE_KEY/versions/1
    env: 'KEY'
images:
  - "us-west2-docker.pkg.dev/$PROJECT_ID/foodtok-backend-repo/foodtok-backend"