-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public."Users"
(
    _id uuid NOT NULL,
    name character varying(26) COLLATE pg_catalog."default" NOT NULL,
    "displayName" character varying(26) COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "Users_pkey" PRIMARY KEY (_id),
    CONSTRAINT "Users_name_key" UNIQUE (name),
    CONSTRAINT "Users_AuthID_fk" FOREIGN KEY (_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Users"
    OWNER to postgres;

GRANT ALL ON TABLE public."Users" TO anon;

GRANT ALL ON TABLE public."Users" TO authenticated;

GRANT ALL ON TABLE public."Users" TO postgres;

GRANT ALL ON TABLE public."Users" TO service_role;
