-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public."Categories"
(
    _id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(16) COLLATE pg_catalog."default" NOT NULL,
    "UserId" uuid NOT NULL,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "Categories_pkey" PRIMARY KEY (_id),
    CONSTRAINT "Categories_name_key" UNIQUE ("UserId", name),
    CONSTRAINT "Categories_UserId_fk" FOREIGN KEY ("UserId")
        REFERENCES public."Users" (_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Categories"
    OWNER to postgres;

GRANT ALL ON TABLE public."Categories" TO anon;

GRANT ALL ON TABLE public."Categories" TO authenticated;

GRANT ALL ON TABLE public."Categories" TO postgres;

GRANT ALL ON TABLE public."Categories" TO service_role;

CREATE TABLE IF NOT EXISTS public."Ingredients"
(
    _id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(16) COLLATE pg_catalog."default" NOT NULL,
    "UserId" uuid NOT NULL,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "Ingredients_pkey" PRIMARY KEY (_id),
    CONSTRAINT "Ingredients_name_key" UNIQUE (name),
        CONSTRAINT "Ingredients_UserId_fk" FOREIGN KEY ("UserId")
        REFERENCES public."Users" (_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Ingredients"
    OWNER to postgres;

GRANT ALL ON TABLE public."Ingredients" TO anon;

GRANT ALL ON TABLE public."Ingredients" TO authenticated;

GRANT ALL ON TABLE public."Ingredients" TO postgres;

GRANT ALL ON TABLE public."Ingredients" TO service_role;
